### ISSUE TITLE
[enhancement] Compatibility with Reactive Alchemy

### ISSUE THREAD

**Issue by Tysos24** [ssblur/scriptor#117]
There's another magic mod focused on world-by-world experimentation, Reactive Alchemy, that seems like it could work well with Scriptor. I'm not entirely sure what compatibility might entail, but something like using spells to catalyze reactions could harmonize the two mods.
To be honest, I haven't actually had time to try either mod out, but from what I've seen in previews of both, there is strong potential.

**Comment by ssblur** [comment]
This seems interesting, I'll definitely look into adding some compat! Thank you for the suggestion!

**Comment by Tysos24** [comment]
Also maybe the Chalk mod?

**Comment by ssblur** [comment]
Closing this for the moment, as it is not yet on 1.21 and I could not figure out any interesting way to implement compatibility. I will be keeping this in mind, however, so I still appreciate the suggestion!
