### ISSUE TITLE
Customization question

### ISSUE THREAD

**Issue by Raia05** [ssblur/scriptor#118]
is there a way to customize what particles are used for projectiles and more AOE spells? the default dust particles with colors are customizable but simply don't fit the vibe I'm going for.

**Comment by ssblur** [comment]
Unfortunately if your version has dust particles, that means it's an older version of MC, which no longer receive updates. Newer versions have a custom particle which can be textured.

AOE modifiers are currently planned.

Thank you for the suggestions!
