### ISSUE TITLE
[bug] Scrap tier 1 cant result in scrap for lime color

### ISSUE THREAD

**Issue by Rymka69** [ssblur/scriptor#119]
**Mod Version (e.g. Fabric 0.3.4)**: 1.0.4

**What you expect to happen**:
At least sometimes a sccrap for the word for lime color should appear

**What actually happens**:
I tried like 6 stacks of scrap tier 1, and none of them were for lime, all other colors appearing at least 10 times

**Comment by ssblur** [comment]
Confirmed lime can be obtained for tier 1 scraps. It would appear you were just unlucky. If opening issues in the future, please confirm the loader / MC version you are using as well.
