### ISSUE TITLE
[enhancement] Compatibility With Scholar

### ISSUE THREAD

**Issue by LifeReaper** [ssblur/scriptor#121]
I don't know if it's possible, but scholar is a great mod for letting you edit books and has the ability to show two pages at a time. This would add to the immersion of creating a dictionary in game using writable books. I've noticed that the scholar UI opens every time you cast a spell from a written book as well.

**Comment by ssblur** [comment]
I am currently working on features which should bridge this gap, though due to availability this will likely not manifest as Scholar compat. As such, I'll be closing this issue. 

That being said, thank you for the suggestion!
