### ISSUE TITLE
[enhancement]

### ISSUE THREAD

**Issue by Creativious** [ssblur/scriptor#123]
So I've been messing around with the mod for a bit, and I've gotten a decent grasp of it, but my issue with the the and descriptor thing or well it's not even a descriptor. There's only one spell that I could find that uses "other:and" and it seems to add extra actions. It would be nice if it could also duplicate subjects, such as projectile + and + storm + lightning which could maybe shoot out a projectile causing a storm that would then spawn lightning.

**Comment by ssblur** [comment]
Thank you for the suggestion! To mitigate the complexity of spells (from the processor's perspective, at least), the closest to this that I currently plan to add to Scriptor are target modifiers, some of which are already in! Either way, I appreciate the feedback, and will continue to work on improving the mod.
