### ISSUE TITLE
Book Of Book Empty Crash[bug]

### ISSUE THREAD

**Issue by TrulyTails** [ssblur/scriptor#124]
**Mod Version (e.g. Fabric 0.3.4)**: 1.1.4. 1.20.4

**What you expect to happen**: Nothing
A brief description of what you think should happen.

**What actually happens**: The game crashes when using the Book Of Book scroll feature with no spells inside of it.
Step 1: Have a Book Of Book with no spells
Step 2: Shift + Scroll with BoB in hand.

**Comment by ssblur** [comment]
Thank you for reporting. This has been fixed, the fix should be available in the next update.
