### ISSUE TITLE
[enhancement] Chalk mod compatibility

### ISSUE THREAD

**Issue by Tysos24** [ssblur/scriptor#125]
This might be hard (I wouldn't know), but you could make it so that chalk from the Chalk mod works like Scriptor chalk when renamed to allow for more colorful spells and, of course, better compatibility.

**Comment by ssblur** [comment]
While multicolored chalk may eventually be added to scriptor, after extensive review I do not believe that I can meaningfully add chalk mod compatibility.

Either way, thank you for your suggestion!
