### ISSUE TITLE
chalk crashes other players [bug] 

### ISSUE THREAD

**Issue by ipypka** [ssblur/scriptor#126]
Mod Version fabric 1.0.4 - 1.20.1

there is no good discription (in patchouli) for what a chalk circle is, or how to use it, accidentaly i figured that holding it and draging to another block makes (something that vaguelylooks like) a connection, so i tried making various squares (3x3, 4x4, 5x5) and right click the one that has text (the spell)

**What you expect to happen**:
a line extends as i drag the camera (and right clicking the one with text activating it (not a part of a bug but please add a description on how to use it))

**What actually happens**:
up to a dosen of chalk "blocks" (the ones with text) appear (some on top of eachother) 

teps here on how to reproduce the issue:
m2 + drag camera (mayhaps shift was involved (will update this (is possible) in the next 24 hours)

hope any of those words make sence in that order, or even help

**Comment by ssblur** [comment]
I'm confused as to how you're getting the results you're seeing, chalk writes words one at a time on the ground after it's named and you construct a spell as normal. I think the lines may just be connections between chalk blocks, which indicate that they are part of the same spell. Either way I will work on improving the documentation.

Can you provide crash reports for those who crashed? If so I will work to get that sorted.

**Comment by ipypka** [comment]
first of all, it turn out i am a illiterate slug, but even with that in
place, you should change the name of it to something that does describes it
better
second, it was a kick, not a crash, but still bad
third, if you shift + right click, and without releasing any of those, look
at other blocks, sometimes, rarely, no chalk will be placed, only for all
of it to appear a second or two later, that is what happen. Placing chalk
generally stresses the server

i failed to replicate the issue and were completely wrong about the
mechanics
now i will go live at the bottom of the well, forever, where i will never
bother anyone with my idiocy

good luck to you, really like your mod!

ср, 12 июн. 2024 г. в 01:11, Pat Hallbick ***@***.***>:
>
> I'm confused as to how you're getting the results you're seeing, chalk
writes words one at a time on the ground after it's named and you construct
a spell as normal. I think the lines may just be connections between chalk
blocks, which indicate that they are part of the same spell. Either way I
will work on improving the documentation.
>
> Can you provide crash reports for those who crashed? If so I will work to
get that sorted.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
***@***.***>
