### ISSUE TITLE
[bug] Could not execute entrypoint stage 'main' due to errors, provided by 'scriptor'!

### ISSUE THREAD

**Issue by Gilithrimm** [ssblur/scriptor#132]
**Mod Version (e.g. Fabric 0.3.4)**: 
Fabric 1.2.2

**What you expect to happen**:
A game should launch

**What actually happens**:
Game crashes during loading

**Steps to reproduce**:

1. Install fabric 0.15.11 as described [here](https://docs.fabricmc.net/players/installing-fabric)
2. Download & add fabric-api 0.100.7 for 1.21, scriptor 1.2.2 for 1.21 and architectury 13.0.4 for 1.21
3. Launch the game

**Additional files**:
[latest.log](https://github.com/user-attachments/files/16286815/latest.log)

[scriptor.log](https://github.com/user-attachments/files/16286821/scriptor.log)

**Comment by Gilithrimm** [comment]
downgrading this mod to 1.2.1 makes the issue disappear

**Comment by ssblur** [comment]
It appears your latest.log was cut off, could you submit a version which includes the error you are encountering?

**Comment by ssblur** [comment]
Thank you, looks like that included the error. Give me a moment, going to test some changes and should have a fix up shortly. Appreciate the report!

**Comment by Gilithrimm** [comment]
Thank you for responding and fixing it so fast!
