### ISSUE TITLE
[bug] Crafting Recipes non Functional 

### ISSUE THREAD

**Issue by Tr1ggerfish1** [ssblur/scriptor#133]
Fabric 0.16.0
scriptor-1.2.3-1.21-fabric-sgd.jar:

Recipes Should be craftable:

mods installed:
fabric-api-0.100.7+1.21.jar
architectury-13.0.4-fabric.jar
jei-1.21-fabric-19.5.0.42.jar
*<- shown in log not relevant to bug stated
*alloy-forgery-2.2.2+1.21.jar
*owo-lib-0.12.10+1.21.jar

[latest.log](https://github.com/user-attachments/files/16318922/latest.log)

![image](https://github.com/user-attachments/assets/8f64cbc8-67bd-4ece-9d3b-c0f0d464e344)

**Comment by ssblur** [comment]
Apologies, been out of town. Testing, but this should be fixed shortly. Thank you for letting me know.
