### ISSUE TITLE
[bug] Patchouli guide does not spawn in

### ISSUE THREAD

**Issue by Zevyrus** [ssblur/scriptor#134]
**Mod Version (e.g. Fabric 0.3.4)**: 1.2.1-1.20.1-fabric

**What you expect to happen**:
Upon dusting off a tome, receive patchouli scriptor guidebook

**What actually happens**:
When the player dusts off their first tome, no guidebook is dropped into the player's inventory, but it can still be accessed via /open-patchouli-guidebook. However it cannot be spawned in through /give, making accessing it a little out of the way.

**Comment by ssblur** [comment]
This appears to be tied to broken Advancements in that version, I'll try to get that sorted. Thank you for the report!

**Comment by ssblur** [comment]
This should be fixed in 1.2.2 for 1.20.1. Thank you again for letting me know!

**Comment by Zevyrus** [comment]
thank you so much!
