### ISSUE TITLE
[bug][NeoForge] java.lang.IllegalAccessError when joining new world

### ISSUE THREAD

**Issue by LDiarth** [ssblur/scriptor#135]
**Mod Version (e.g. Fabric 0.3.4)**:
NeoForge 21.0.145
Architectury 13.0.6
Scriptor 1.2.7-1.21

**What you expect to happen**:
Can create and join a new world.

**What actually happens**:
Server crashes when attempting to join newly created world.

[crash-2024-07-29_19.30.02-server.txt](https://github.com/user-attachments/files/16417500/crash-2024-07-29_19.30.02-server.txt)

**Comment by ssblur** [comment]
Thanks for the report! A version is being built that resolves this issue, and should be available on Releases, Modrinth, and CurseForge shortly.
