### ISSUE TITLE
[bug] Minecraft crashing due to the "mute" effect

### ISSUE THREAD

**Issue by Tanjiraaaaa** [ssblur/scriptor#139]
**Mod Version (e.g. Fabric 0.3.4)**:
0.16.0
**What you expect to happen**:
Nothing

**What actually happens**:
Crash 
here are the [crash logs
](https://mclo.gs/FTDNpBY)

**Comment by ssblur** [comment]
This has already been fixed. Please update Scriptor to the latest version (1.2.10 for 1.21 at time of writing).

That being said, thank you for reporting!
