### ISSUE TITLE
[bug] Wild phasing effect crashes the game

### ISSUE THREAD

**Issue by Tanjiraaaaa** [ssblur/scriptor#140]
**Mod Version (e.g. Fabric 0.3.4)**:
0.16.0
**What you expect to happen**:
Game should not crash

**What actually happens**:
Game crashes
I don't know exactly what the steps are but I do have the [crash logs](https://mclo.gs/8gnSpgz) here

**Comment by Tanjiraaaaa** [comment]
From what I heard, it crashes only when used in the nether

**Comment by ssblur** [comment]
This seems to be related to level saving when using Architectury's RegistryHolders directly. Thank you for the report, this should be fixed in the next release.
