### ISSUE TITLE
[bug] Coordinate-focused crystal not attuning

### ISSUE THREAD

**Issue by MarieNobody** [ssblur/scriptor#142]
**Mod Version (e.g. Fabric 0.3.4)**:

1.2.10-1.21-fabric

**What you expect to happen**:
When using a coordinate-focused crystal while facing a side of the block, the position of that block should be registered in the crystal, probably indicated in the tooltip. Then, when placed on a casting lectern with a valid spell, that spell would happen

**What actually happens**:
When using a coordinate-focused crystal while facing a block, the crystal doesn't move, its tooltip doesn't update (which the player-focused crystal do), and when placed on a casting lectern the spell doesn't happen, despite the spell working when cast with a player-focused crystal

**Comment by ssblur** [comment]
Thank you for the report, this is fixed in an upcoming release.
