### ISSUE TITLE
[Suggestion] Describe the mod's capabilities more on mod page

### ISSUE THREAD

**Issue by FyreAlchemage** [ssblur/scriptor#19]
The Modrinth page for this mod doesn't exactly tell what the spells in it are capable of doing - interesting mechanics are all well and good but one doesn't know what niches it could occupy.

Would it be reasonable to list somewhere what the spells may do?

**Comment by ssblur** [comment]
Thank you for the suggestion! While I never intend to explicitly list available spell effects, I do plan to improve documentation in a future update, as well as including some documentation in-game.

Leaving this issue open until documentation changes are merged.

**Comment by ssblur** [comment]
Updated documentation for existing features, and have changes planned for all future changes. Next release will push links to documentation to mod pages.
