### ISSUE TITLE
[Suggestion] Spell Obfuscation

### ISSUE THREAD

**Issue by Theov0re** [ssblur/scriptor#39]
Basically, I was wondering if it would be possible to create spells but then somehow lock them, so that others cannot view the formula contained within. So, they can use the book but cannot decipher the spell. I can see this being a bit difficult with the spellbooks, but perhaps there could be some kind of limited-use item that cast the spell but whose formula you couldn't read? Obviously, this isn't really useful for Singleplayer, but it would be a nice feature for Multiplayer.

**Comment by ssblur** [comment]
This is an interesting idea, and one I will keep in mind when working on subsequent versions. I am exploring adding additional ways of writing spells, which I may use to flesh this idea out.

Preserving this issue until I either implement or decide against this feature.

**Comment by ssblur** [comment]
This has been added to the mod. The version with this feature will go up soon. Just craft a book with a Glow Ink Sac. Have fun!
