### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Rose-French** [ssblur/scriptor#4]
(This is Mail by the way, I'm using my friend's github at the moment)
[crash-2023-01-24_21.03.59-client.txt](https://github.com/ssblur/scriptor/files/10497184/crash-2023-01-24_21.03.59-client.txt)

**Comment by ssblur** [comment]
This appears to have been an issue with the Modrinth uploadFile task, this has been manually corrected, and Commit 44707e624b44ec028f7ad5b37269b5aec29b87be should correct this issue moving forward.

Please confirm if this issue is resolved by redownloading the mod from Modrinth.

**Comment by ssblur** [comment]
![image](https://user-images.githubusercontent.com/7095706/214689075-08b07d33-d43f-4a2d-9bbf-2102b45b4d88.png)
