### ISSUE TITLE
[bug] Spell Scrolls Appearing With Spellbook

### ISSUE THREAD

**Issue by Theov0re** [ssblur/scriptor#40]
**Mod Version (e.g. Fabric 0.3.4)**: The latest version as of now, [0.3.5-FABRIC](https://modrinth.com/mod/scriptor-magicae/version/47y3hCt0)

**What you expect to happen**: Separate loot?
A brief description of what you think should happen. _Basically, I imagine that identify scrolls should be relatively rare and that they don't spawn with every spellbook._

**What actually happens**: I always find an Identify Scroll alongside any Spell.
What actually happens, in detail. If you can, include steps here on how to reproduce the issue. _Currently, in seemingly any chest I open, if there is a spellbook in it, there is also an identify scroll. As for how to reproduce the issue...IDK just load a world? I am using other mods, but I don't think any of them should be modifying loot tables, so I believe this problem lies in this mod._

**Comment by ssblur** [comment]
Thank you for reporting this!

This isn't a bug per se, as much as something I hadn't gotten to yet. In 0.3.5, Identify Scrolls don't have a rarity modifier attached to them, so will always spawn in valid chests. This will change in the next version, which should resolve this issue. This version should release within the next week or so.
