### ISSUE TITLE
[bug] Dedicated server crash

### ISSUE THREAD

**Issue by Alexander3847575** [ssblur/scriptor#43]
**Mod Version (e.g. Fabric 0.3.4)**:
Forge 0.3.5 for forge 1.19.2 43.2.4

**What you expect to happen**:
A brief description of what you think should happen.
No crash

**What actually happens**:
What actually happens, in detail. If you can, include steps here on how to reproduce the issue.

Crash on occasion: See attached crash report, it seemed to occur after a player unlocked a new spell sometimes... it seems very hard to pin down the exact cause but it may be an issue that rarely occurs in an dedicated server environment. If there's any other info I can provide please do tell, and I'll let you know if we run into it again.

[crash-2023-04-25_01.39.33-server.txt](https://github.com/ssblur/scriptor/files/11316010/crash-2023-04-25_01.39.33-server.txt)

**Comment by ssblur** [comment]
This issue should be resolved in the next version, which I will be pushing shortly. Thank you for reporting.
