### ISSUE TITLE
[bug] Crashing on a dedicated server

### ISSUE THREAD

**Issue by noncom** [ssblur/scriptor#49]
**Mod Version (e.g. Fabric 0.3.4)**: scriptor-0.4.2-forge.jar

**What you expect to happen**: No crash on dedicated server

**What actually happens**: The mod crashes the dedicated server on startup. Apparently it requests some client-side renderer-related stuff.

The crashlog is attached.

[crash-2023-04-29_21.31.06-fml.txt](https://github.com/ssblur/scriptor/files/11359858/crash-2023-04-29_21.31.06-fml.txt)

**Comment by ssblur** [comment]
Didn't notice this because my IDE was messing up on Forge tasks, apologies. Should be fixed in 0.4.3, which is going up shortly.

**Comment by noncom** [comment]
Yeah, that happens! Awesome, thanks! :)
