### ISSUE TITLE
[bug] Chat validation error

### ISSUE THREAD

**Issue by ElNico56** [ssblur/scriptor#51]
**Mod Version (Fabric 0.4.3)**:

**What you expect to happen**:
Chat message casts the spell normally.

**What actually happens**:
Chat message breaks something and kicks me out of the world with the message "Chat message validation failure".

![2023-05-21_14 28 05](https://github.com/ssblur/scriptor/assets/18220871/abda2a37-1a7f-4716-9d3f-2a552ca95c78)

[scriptor_dictionary.zip](https://github.com/ssblur/scriptor/files/11525283/scriptor_dictionary.zip)

**Comment by ssblur** [comment]
Thank you for reporting. What was the text of the spell you were trying to cast?

**Comment by ssblur** [comment]
On version 0.4.3, using the provided scriptor_dictionary.dat. Tested in online and offline mode on a dedicated server, unable to replicate after casting every default spell a few dozen times each and intentionally fizzling or miscasting. There's a chance this is either a mod conflict or an unrelated chat validation error.

Do you have other mods installed? If so, could you list those here? Does this error occur in singleplayer or on a dedicated server, and if the latter, were there other players online?

**Comment by ssblur** [comment]
Info not available, can't replicate issue, closing
