### ISSUE TITLE
[Feature Request] Chiseled Bookshelf compatibility

### ISSUE THREAD

**Issue by Xicad** [ssblur/scriptor#58]
Being able to put tomes and spellbooks in chiseled bookshelves would be nice and would be consistent with vanilla allowing all types of books.

**Comment by ssblur** [comment]
Thank you for the suggestion! I've added this to the roadmap.

**Comment by ssblur** [comment]
OK well that was very easy. Just added it to the appropriate tag, it'll be in the next version. Thanks again for the suggestion!
