### ISSUE TITLE
[Bug] 0.6.0 crash on startup

### ISSUE THREAD

**Issue by Xicad** [ssblur/scriptor#61]
https://pastebin.com/TXpz89vr 

looks like smth related to the new lectern thing

Minecraft 1.20.1, Fabric version 0.14.21

**Comment by ssblur** [comment]
Building a fix right now, looks like refmaps are only generated for the common mixin at the moment. Once 0.6.1 is up this should be fixed, sorry for the trouble and thank you for the report.
