### ISSUE TITLE
[bug] spellbook recipe not working

### ISSUE THREAD

**Issue by madmanen** [ssblur/scriptor#62]
**Mod Version (e.g. Fabric 0.3.4)**:

**What you expect to happen**:
Being able to craft spellbooks

**What actually happens**:
no matter the configuration in the crafting table ( no matter if it's with a signed, unsigned or plain book) nothing happens
I was trying to make a copy of the magelight spell.
![image](https://github.com/ssblur/scriptor/assets/137783354/88774efe-ea7f-4fc7-a1c2-456e08fdf39f)

**Comment by ssblur** [comment]
What version of the mod are you on, what version of Minecraft are you on, and what mod loader are you using? Prior to 1.20 versions, Spellbooks were crafted using the Smithing Table.

**Comment by madmanen** [comment]
> What version of the mod are you on, what version of Minecraft are you on, and what mod loader are you using? Prior to 1.20 versions, Spellbooks were crafted using the Smithing Table.

Ah that explains it, sorry.
I was playing on minecraft version 1.9.4 and was using the guide to basics yt video as a reference so the thought that it would have been a different crafting bench didn't occur to me.

**Comment by ssblur** [comment]
No worries, sorry that wasn't super clear. You can always check recipes in game using JEI or a similar mod!
