### ISSUE TITLE
[enhancement] Visual Overhaul?

### ISSUE THREAD

**Issue by Woof6968** [ssblur/scriptor#64]
The visual effects do leave things to be desired, the mechanics are well and good, but simple particle effects from base minecraft can be unattractive for those used to modded effects, so maybe some more flashiness would be a welcome addition to this mod, and make it have the same attraction as things like ars nouveau. just a suggestion

**Comment by ssblur** [comment]
I will be doing this, but it is not a priority, as I'm still trying to finish much of the base mod.
Thank you for the suggestion!

**Comment by ssblur** [comment]
The latest update adds new particles, some new renderers / models, and some other polish like sound effects. I'll close this issue when it is merged into main.
