### ISSUE TITLE
[bug] Scriptor has a verbal spell incompatibility with Minecraft Comes Alive Reborn's chat AI

### ISSUE THREAD

**Issue by aegiro** [ssblur/scriptor#65]
**Mod Version (e.g. Fabric 0.3.4)**: Quilt 0.6.1
**What you expect to happen**:
When I say a villager's name the chat AI generates a response.

**What actually happens**:
Villager does not respond.

**Comment by ssblur** [comment]
Have you tested this functionality in-game without Scriptor installed? This functionality appears to work identically with and without Scriptor installed.

**Comment by ssblur** [comment]
Cannot replicate this issue, cannot get other users to replicate it, no response here or on Discord. Closing this issue, please feel free to reopen if you are still experiencing problems.
