### ISSUE TITLE
[enhancement] Cast enchants.

### ISSUE THREAD

**Issue by KingAlexey212** [ssblur/scriptor#66]
Enchantments are kind of magic, so I think it would be cool if you'll be able to apply vanilla enchantments on items using spells.

**Comment by ssblur** [comment]
Have considered adding this, need to find a way to do it that is interesting and doesn't create one-use words.

**Comment by ssblur** [comment]
Vanilla enchantments are not being implemented exactly, but a unique enchantment / tool system is being implemented that I feel will fill the same niche. Thank you for your suggestion.
