### ISSUE TITLE
[bug] mod throws  java.lang.reflect.InvocationTargetException error on startup

### ISSUE THREAD

**Issue by AbstractestThought** [ssblur/scriptor#72]
**Mod Version (e.g. Fabric 0.3.4)**: Forge 44.1.23

**What you expect to happen**:
Minecraft loads to the main screen without any issue

**What actually happens**:
A screen pops up saying that Scriptor failed to load, giving this reason:  java.lang.reflect.InvocationTargetException
To reproduce:

1. Install Forge 44.1.23
2. (Maybe what is causing the issue) Install Optifine and GeckoLib and possibly cave noise mod as well as Scriptor for 1.19.3.
3. Start Minecraft

**Comment by ssblur** [comment]
Presuming you are on Scriptor 0.5.0-1.19.3. Cannot replicate with GeckoLib, OptiFine, and Forge 44.1.23. May be a compatibility with "cave noise mod" but I am unsure which mod this is. Can you provide a link?

Thank you in advance.

**Comment by AbstractestThought** [comment]
@ssblur https://www.curseforge.com/minecraft/mc-mods/cave-dweller I guess it's called Cave Dweller now

**Comment by ssblur** [comment]
Have you installed Architectury? This is a required dependency of Scriptor.

**Comment by AbstractestThought** [comment]
Lol no I have not, I’m sorry. I looked in the description when I downloaded it to see if there were any dependencies but I guess I didn’t see that. So sorry for wasting your time with a nonexistent issue. Still kinda weird that it threw an error instead of saying that it required Architectury though

**Comment by ssblur** [comment]
No worries, thank you for reporting!
