### ISSUE TITLE
[bug] Binders do not work in 1.19.3

### ISSUE THREAD

**Issue by AbstractestThought** [ssblur/scriptor#74]
**Mod Version (e.g. Fabric 0.3.4)**: Forge 0.5.0

**What you expect to happen**:
Putting a spell book in a crafting table with a mundane leather binder crafts a normal written book and putting a written book in a crafting table with a spellbook binder creates a spellbook.

**What actually happens**:
Both recipes do nothing.
To reproduce, either:

1. Get a spellbook from a tome.
2. Try to craft a spellbook with the mundane leather binder
or
1. Write a spell in a book and quill
2. Sign the book and quill
3. Try to craft the book and quill with a spellbook binder

I'm really sorry if this is just me being dumb again. Love the mod by the way.

**Comment by ssblur** [comment]
Prior to 1.20, spellbooks are crafted in the Smithing Table using the same ingredients.
