### ISSUE TITLE
[bug] Rune visual invisible with shader

### ISSUE THREAD

**Issue by GeekyBakerBen** [ssblur/scriptor#77]
Version details:
Minecraft 1.20.1
Scriptor mod 0.6.6 for Fabric

I'm reasonably certain that this is just going to be closed as a "can't do anything about it" incompatibility issue but, the placed runes are invisible while using ComplementaryReimagined shader via Iris. Don't know if it happens with other shaders or not, but I know that I can only see the rune effect if I turn the shaders off.

Don't get me wrong, it makes for some AWESOME invisible traps xD but it isn't the best for making it look good.

**Comment by ssblur** [comment]
Have tested a number of things, cannot get visuals working consistently across shaders, apologies. Will be consulting with some other devs more familiar in the future, but for now marking as wontfix and closing. Either way, thank you for reporting this issue.
