### ISSUE TITLE
[bug] Game Crashing with Scriptor enabled

### ISSUE THREAD

**Issue by sdfghjerh** [ssblur/scriptor#78]
every time i use the mod it crashes but every other mod doesn't

**Comment by ssblur** [comment]
Hello! Can you provide more information?

How did you install Scriptor, what modloader are you on, what version of Scriptor are you using, did you install dependencies for whichever version you are on (Quilted Fabric API + Architectury API for Quilt, Fabric API + Architectury API for Fabric, or Architectury API for Forge), are you receiving any kind of message on crash, and have you actually booted your game with all mods except Scriptor enabled?

**Comment by ssblur** [comment]
If you get any more information, please feel free to reopen this issue, I am closing it for now. Thank you for your report.
