### ISSUE TITLE
[book text is displayed properly only in the right hand]

### ISSUE THREAD

**Issue by eternalsulfur** [ssblur/scriptor#82]
scriptor-0.6.6-1.21.1-sgd-fabric:

i expected to see text in the book

the text is displayed in air. im holding book in the left hand as a main hand, but text is still at right side, floating. it also happens when i hold it in the right hand, as in the screenshots.
![2023-11-01_19 03 05](https://github.com/ssblur/scriptor/assets/63477524/f99d81db-03a2-49db-9cad-e684401d57a3)
![2023-11-01_19 07 48](https://github.com/ssblur/scriptor/assets/63477524/a90f82e7-a672-49a2-8a6b-8f064558915c)

**Comment by ssblur** [comment]
Thank you for reporting this issue!

User CyberneticSquid committed a fix for this in #79 

This should be resolved in the next major version.
