### ISSUE TITLE
[bug] Broken spells getting generated on 1.19.2 on quilt

### ISSUE THREAD

**Issue by Kobold111** [ssblur/scriptor#84]
While going through a mine shaft 2 books i got were broken spells specifically inferno (think it was titled something like that) and break block. This also happened with break block again in another world.

**Comment by ssblur** [comment]
Thank you for reporting this. 

Are you on 0.5.0? Can you zip up and attach the scriptor_dictionary.dat file from your save folder?

**Comment by Kobold111** [comment]
I am sorry but i deleted the world i was originally having this error on and could not replicate it after generating 3 different world. Here is my list of mods and i am using the latest quilt API for 1.19.2

Dramatic Doors
FizzWare
DramaticDoors-QuiFabrge-1.19.2-3.1.5.jar
Incendium
Starmute
Incendium_1.19.3_v5.1.6.jar
[FABRIC/QUILT] Disable Custom Worlds Advice
Nara
DisableCustomWorldsAdvice-3.0.jar
Alloy Forgery
gliscowo
wraith-alloy-forgery-2.0.20+1.19.jar
Architectury API (Fabric/Forge)
shedaniel
architectury-6.5.85-fabric.jar
AttributeFix
DarkhaxDev
AttributeFix-Fabric-1.19.2-17.2.7.jar
bad packets
badasintended
badpackets-fabric-0.2.3.jar
Besmirchment 2
MrSterner_
besmirchment-1.19.2-11.jar
Bewitchment
MoriyaShiine
bewitchment-1.19-7.jar
Black Powder
AmyMialee
blackpowder-2.0.0.jar
Boat Break Fix [Neo/Forge/Fabric/Quilt]
ElocinDev
BoatBreakFix-Universal-1.0.2.jar
Bone Zone
DarkhaxDev
BoneZone-Fabric-1.19.2-1.0.3.jar
Bookshelf
DarkhaxDev
Bookshelf-Fabric-1.19.2-16.3.20.jar
Bottle Your Xp
Serilum
bottleyourxp-1.19.2-3.2.jar
Breedable Killer Rabbit
Serilum
breedablekillerrabbit-1.19.2-3.3.jar
Bygone Nether (Fabric)
izofar
bygonenether-1.19-1.3.2.jar
Cardinal Components API
UpcraftLP
cardinal-components-api-5.0.2.jar
Charm
svenhjol
charm-fabric-1.19.2-4.4.4.jar
ChoiceTheorem's Overhauled Village
ChoiceTheorem
ctov-3.2.6b.jar
CleanCut
Rongmario
cleancut-6.0.jar
Collective
Serilum
collective-1.19.2-7.7.jar
Conduits Prevent Drowned
Serilum
conduitspreventdrowned-1.19.2-3.5.jar
Conjuring
gliscowo
conjuring-1.0.26+1.19.jar
Consecration (Fabric/Forge/Quilt)
TheIllusiveC4
consecration-quilt-6.0.1+1.19.2.jar
Create Big Cannons
rbasamoyai
createbigcannons-fabric-1.19.2-0.5.2.a.jar
Create Fabric
tropheusj
create-fabric-0.5.1-c-build.1160+mc1.19.2.jar
Create: Bells & Whistles
sudolev
bellsandwhistles-0.4.4+1.19.2-12.jar
Create: Ender Transmission
Forsteri123
createendertransmission-2.0.6-1.19.2-fabric.jar
Create: Steam 'n' Rails
mattentosh
Steam_Rails-1.5.1+fabric-mc1.19.2.jar
Creeper Spores
PyrofabTheModsmith
creeper-spores-1.9.1.jar
Dark Rites 2
MrSterner_
darkrites-1.0.0+1.19.2.jar
Debugify
XanderIsDev
Debugify-2.8.0.jar
Decorative Blocks (Fork)
TheWinABagel
Decorative Blocks-fabric-1.19.2-3.1.1.jar
Despawning Eggs Hatch
Serilum
despawningeggshatch-1.19.2-4.2.jar
Dismount Entity
Serilum
dismountentity-1.19.2-3.1.jar
Dynamic Asset Generator
lukebemish
dynamic_asset_generator-quilt-1.19.2-1.2.0.jar
Effective
doctor4t
effective-2.1.1+1.19.2.jar
Enchantment Descriptions
DarkhaxDev
EnchantmentDescriptions-Fabric-1.19.2-13.0.16.jar
End Portal Recipe
Serilum
endportalrecipe-1.19.2-5.1.jar
Excavated Variants
lukebemish
excavated_variants-quilt-1.19.2-1.0.3.jar
Extract Poison
Serilum
extractpoison-1.19.2-3.2.jar
Fall Through Slime
Serilum
fallthroughslime-1.19.2-3.1.jar
Fastload
StockiesLad
Fastload+1.18.2-1.20-3.4.0.jar
Fixed Anvil Repair Cost
Serilum
fixedanvilrepaircost-1.19.2-3.2.jar
Forgotten Features [FABRIC]
Cristelknight
forgotten_features-1.6+1.19.2.jar
FPS Reducer
bre2el
FpsReducer2-fabric-1.19.2-2.1.jar
Friends&Foes (Fabric) (Copper Golem, Glare, Moobloom, Iceologer, Barnacle, Wildfire, Illusioner, Rascal and Tuff Golem)
Faboslav
friendsandfoes-fabric-mc1.19.2-1.8.10.jar
From The Fog
LunarEclipseStudios
From-The-Fog-1.19-v1.9-Forge-Fabric.jar
Fusion (Connected Textures)
SuperMartijn642
fusion-1.1.0c-fabric-mc1.19.2.jar
GeckoLib
Gecko
geckolib-quilt-1.19-3.1.41.jar
Geode+ [Forge/Fabric]
YeoXuHang
geodefabric-1.1.8-1.19.2.jar
Get Pricked!
naomi
get-pricked-1.0.0.jar
Glow Ink Plus
anvian
(Fabric)GlowInkPlus-1.19.x-1.2.0.jar
Grabby Mobs
Serilum
grabbymobs-1.19.2-1.2.jar
Haema
the_will_bl
haema-1.10.4+1.19.jar
Improved End
RupyberStudios
improved_end-1.19.2-1.0.6.jar
Indium
comp500
indium-1.0.9+mc1.19.2.jar
LambDynamicLights
LambdAurora
lambdynamiclights-2.2.0+1.19.2.jar
Let Me Despawn
frikinjay
letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar
Luna Slimes
AViewFromTheTop
LunaSlimes-1.6-1.19.2.jar
MidnightLib
TeamMidnightDust
midnightlib-0.6.1.jar
Mimic Mod
RedrixTTV
Mimic-fabric-1.19.1-1.2.38.jar
Miskatonic Mysteries
cybercat5555
miskatonicmysteries-0.1.7.jar
Mod Menu
Prospector
modmenu-4.2.0-beta.2.jar
Model Gap Fix
MehVahdJukaar
modelfix-1.7-universal.jar
More Brewable Potions
MR_LOLF_
morepotions-1.0.2.jar
Mystic Potions
creep3rcrafter
MysticPotions-1.1.2-1.19.2-Quilt.jar
Naturalist
Starfish_Studios
naturalist-fabric-4.0.3-1.19.2.jar
Necronomicon API
ElocinDev
Necronomicon-Fabric-1.3.0.jar
Nether Depths Upgrade
scouter567
netherdepthsupgrade-fabric-3.1.1-1.19.2.jar
Nether Mooshrooms
An_Sar
NetherMooshrooms-1.1-1.19.2-fabric.jar
Nether Portal Spread
Serilum
netherportalspread-1.19.2-7.6.jar
Not Just Biomes
Apollo
not-just-biomes-mc1.19.2-1.0.1.jar
Nutritious Milk
Serilum
nutritiousmilk-1.19.2-3.2.jar
Nyf's Quivers
Nyfaria
nyfsquiver-Fabric-0.5.1-1.19.2.jar
Origins (Fabric)
Apace
Origins-1.19.2-1.7.1.jar
oωo (owo-lib)
gliscowo
owo-lib-0.8.5+1.19.jar
Paradise Lost
ImmortalDevs
paradise-lost-2.1.0-beta+1.19.2.jar
Patchouli (Fabric/Quilt)
williewillus
Patchouli-1.19.2-77-FABRIC.jar
Pehkui
Virtuoel
Pehkui-3.7.11+1.14.4-1.20.2.jar
Placeable Blaze Rods
Serilum
placeableblazerods-1.19.2-3.2.jar
Polymer
Patbox
polymer-all-0.2.28+1.19.2.jar
Potion Particle Pack
AmyMialee
potionparticlepack-1.0.2.jar
Psychedelicraft
Ivorius
psychedelicraft-1.6.6+1.19.2.jar
Pure Amethyst Tools (Fabric/Forge)
purejoshmc
PureAmethystTools-v1.0.0-1.19.2-Fabric.jar
Pure Copper Tools (Fabric/Forge)
purejoshmc
PureCopperTools-v1.0.0-1.19.2-Fabric.jar
Pure Discs - Trails & Tales (Fabric/Forge)
purejoshmc
PureDiscsTrailsTales-v1.0.0-1.19.2-Fabric.jar
Pure Emerald Tools (Fabric/Forge)
purejoshmc
PureEmeraldTools-v1.0.0-1.19.2-Fabric.jar
Pure S'mores (Fabric/Forge)
purejoshmc
PureSmores-v1.0.0-1.19.2-Fabric.jar
Qu Enchantments
QueADV
qu-enchantments-1.2.4-1.19.jar
Quilt Kotlin Libraries (QKL)
QuiltMC
quilt-kotlin-libraries-1.0.2kt.1.8.0flk.1.9.0.jar
Quilted Fabric API (QFAPI) / Quilt Standard Libraries (QSL)
QuiltMC
qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar
Rain Be Gone Ritual
Serilum
rainbegoneritual-1.19.2-3.1.jar
Random Bone Meal Flowers
Serilum
randombonemealflowers-1.19.2-4.4.jar
RAT's Mischief
doctor4t
ratsmischief-2.0.1.jar
Realistic Bees
Serilum
realisticbees-1.19.2-3.5.jar
Realistic Sleep (Fabric/Quilt)
Steveplays28
realisticsleep-1.9.0+mc1.19.x.jar
Repurposed Structures (Quilt/Fabric)
telepathicgrunt
repurposed_structures_quilt-6.3.28+1.19.2.jar
Requiem
PyrofabTheModsmith
requiem-2.0.0-beta.16.jar
Requiem - Pandemonium Expansion
PyrofabTheModsmith
requiem-pandemonium-2.0.0-beta.14.jar
RequiemCrutch
xniki119x
RequiemCrutch-1.0.0+1.19.2.jar
Rideable Ravagers
Mars
rideableravagers-1.19.2-0.jar
Scriptor Magicae
ssblur
scriptor-0.4.5-quilt.jar
Skeleton Horse Spawn
Serilum
skeletonhorsespawn-1.19.2-3.7.jar
Snow Under Trees (Fabric)​
itsmineblock11
snow-under-trees-fabric-1.0.0+1.19.2.jar
Sodium
jellysquid3_
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
Sparse Structures
Maxence
sparsestructures-1.0.jar
Spiders Produce Webs
Serilum
spidersproducewebs-1.19.2-3.2.jar
Structory
botanydev
Structory-1.19-v1.3.jar
Structory: Towers
botanydev
Structory_Towers_1.19_v1.0.1.jar
SuperMartijn642's Config Lib
SuperMartijn642
supermartijn642configlib-1.1.8a-fabric-mc1.19.jar
SuperMartijn642's Core Lib
SuperMartijn642
supermartijn642corelib-1.1.15-fabric-mc1.19.2.jar
Terralith
Starmute
Terralith_1.19.3_v2.3.12.jar
Towns and Towers
Biban_Auriu
Towns-and-Towers-1.19.2-1.9.jar
Trinkets (Fabric)
EmilyPloszaj
trinkets-3.4.2.jar
Universal Graves
Patbox
graves-2.1.3+1.19.2.jar
Visual Overhaul
Motschen
visualoverhaul-4.1.1.jar
Visuality
PinkGoosik
visuality-0.5.6.jar
Wormhole (Portals)
SuperMartijn642
wormhole-1.1.15-fabric-mc1.19.2.jar
WTHIT
badasintended
wthit-quilt-5.19.2.jar
YetAnotherConfigLib
XanderIsDev
YetAnotherConfigLib-2.2.0-for-1.19.2.jar
Zombie Horse Spawn
Serilum
zombiehorsespawn-1.19.2-4.7.jar
