### ISSUE TITLE
[bug] Repair Item spell seems to have an incredibly low cap

### ISSUE THREAD

**Issue by GeekyBakerBen** [ssblur/scriptor#85]
**Mod Version (e.g. Fabric 0.3.4)**:
Fabric 0.6.6-1.21.1

**What you expect to happen**:
Crafted a spell using combination of "Target self + Target target's inventory + Target 1st valid inventory slot + repair/heal + increased power + must be full health" i.e. a slight amendment to the inbuilt "Repair" spellbook.
It should be repeatedly usable to be able to repair my items up to max durability again.

**What actually happens**:
Item heals once, for a small amount. Any subsequent uses seem to cause the item to "pulse" to show that it's being affected correctly, but the durability just doesn't shift at all. Unless I'm misunderstanding that there is some arbitrary soft-cap on the amount of repair an item can receive, I should be able to keep using the spell to repair the item up but after the initial use it just doesn't seem to add any more durability to the item.

**Comment by ssblur** [comment]
Thank you for the report. This definitely seems like a bug, yeah. The repair spell should be able to repair an item to full, though it will do it very slowly, as the amount repaired, depending on the strength modifier used, would only be around 3-5 durability. 

Have you verified the durability isn't changing? Sometimes the change isn't enough to change the appearance of the bar.

Does the default repair spell exhibit the same behavior?

What item are you trying to repair?

Are you in survival mode?

**Comment by GeekyBakerBen** [comment]
I'll keep trying with the spell to see if it makes an eventual difference - might need to find a mod to display the actual numeric value for the durability to test it for certain. Maybe I just had a false sense of hope as the first time I cast it, it made the bar go up a notch.

Yes, the default repair spell is the same behaviour.

In this instance it was a vanilla diamond axe, with Efficiency, Unbreaking, Fortune, and Mending on it, but is the same with any of my gear items.

And yes, this is in survival mode, on my multiplayer server.

I shall test the above further and report back.

**Comment by GeekyBakerBen** [comment]
Ok, I have since tested this with a durability value mod on and I can confirm that this is working as intended. The amounts were just so minor that it didn't make any difference to the visual. Apologies.
