### ISSUE TITLE
question: why generate quilt jar and a fabric jar

### ISSUE THREAD

**Issue by walksanatora** [ssblur/scriptor#9]
doesen't quilt support fabric mods, or is it not 100% compatible

**Comment by ssblur** [comment]
At the moment, it generally supports Fabric mods, yes. Quilt support is explicit for 3 main reasons:

- Potential mod compatibility with Quilt-specific mods.
- Future-proofing for when Quilt drops Fabric support
- It may encourage folks to use Quilt, which I generally prefer to Fabric

Admittedly, the last is to my personal preference, but these were what I had in mind when deciding to publish Quilt versions separately.

Please let me know if you have any other questions, thanks!
