### ISSUE TITLE
[bug] Casting Lecterns cast projectile spells off centre in 1.20.4 Forge

### ISSUE THREAD

**Issue by CodeSaint181** [ssblur/scriptor#97]
**Mod Version**:
Scriptor-1.0.6-1.20.4

**What you expect to happen**:
i expect the lectern to fire the spell down the center of the block as in previous versions

**What actually happens**:
the spell fires off center from the back of the lectern. 
in the images below the lectern fires the default fireball spell from the right side of the back of the lectern and you can see it hugging the wall. In the first image I have put down a anvil to show that it is not a graphical error, as the spell will hug the wall and pass through the gap in the anvil's hitbox to hit the wall behind it.
![image_2024-01-03_065440185](https://github.com/ssblur/scriptor/assets/148516660/92775ea6-7c18-4c85-9063-aa1c39d6b97e)

![image_2024-01-03_065326472](https://github.com/ssblur/scriptor/assets/148516660/1d17d2ec-b679-4b81-ab9a-02093c49fb57)

**Comment by ssblur** [comment]
I see, this is related to a fix for other subjects (specifically runes) on lecterns. I can add a fix for the next version. Thank you for reporting.

**Comment by ssblur** [comment]
I probably won't be pushing a new version until 1.1, since this is noncritical, but this should be fixed in the next version. If you'd like, you can build a version from main to resolve this issue immediately.
